### ISSUE TITLE
Failed update never retried

### ISSUE THREAD

**Issue by Yuav** [thias/puppet-sysctl#15]
sysctl { 'net.ipv4.vs.conntrack': value => '1' }

err 	/Stage[main]/Cisco::Dns::Keepalived/Sysctl[net.ipv4.vs.conntrack]/Exec[sysctl-net.ipv4.vs.conntrack] 	/sbin/sysctl -p /etc/sysctl.d/net.ipv4.vs.conntrack.conf returned 255 instead of one of [0]
err 	/Stage[main]/Cisco::Dns::Keepalived/Sysctl[net.ipv4.vs.conntrack]/Exec[sysctl-net.ipv4.vs.conntrack] 	Failed to call refresh: /sbin/sysctl -p /etc/sysctl.d/net.ipv4.vs.conntrack.conf returned 255 instead of one of [0]
notice 	/Stage[main]/Cisco::Dns::Keepalived/Sysctl[net.ipv4.vs.conntrack]/Exec[sysctl-net.ipv4.vs.conntrack]/returns 	sysctl: cannot stat /proc/sys/net/ipv4/vs/conntrack: No such file or directory
notice 	/Stage[main]/Cisco::Dns::Keepalived/Sysctl[net.ipv4.vs.conntrack]/File[/etc/sysctl.d/net.ipv4.vs.conntrack.conf]/ensure 	defined content as '{md5}9892f17f4768817fea4de8d7bac67fd0'

This option is not retried on the subsequent puppet run. Expectation is that it fails consistently. Module should actively check if the option has the correct value using 'sysctl net.ipv4.vs.conntrack'. This can be done in place of "refreshonly", using an onlyif value != provisioned value

**Comment by thias** [comment]
With the change from #23 and commit f387bb6f6d6b20a433f74aebd243d327d4cade29 this should be solved : All values are now enforced during each puppet run, meaning that any wrong/failing settings will be detected and unavailable key will be retried until finally available.

The above will be available in releases 1.0.3+.
