### ISSUE TITLE
Any chance of a new release?

### ISSUE THREAD

**Issue by robinbowes** [thias/puppet-sysctl#24]
Am currently using my own github fork of this module, but all my changes have been applied to this repo - would be nice to get a new release so I can use the forge instead of github.

**Comment by jlambert121** [comment]
+1

**Comment by tedivm** [comment]
:+1:

**Comment by thias** [comment]
Happening today at last! Sorry for the delay... I have this 9 months old post-it with a section "Forge releases" which I'm taking care of at last :-)
