### ISSUE TITLE
Project URL is wrong

### ISSUE THREAD

**Issue by gjngeldenhuis** [thias/puppet-sysctl#25]
The project URL for this module is wrong in Puppet Forge and just links back to the forge and not the git repository

**Comment by thias** [comment]
Hmmm... interesting. There used to be a link to the source page on the Forge, as I still have "source" pointing to "https://github.com/thias/puppet-sysctl" in the metadata.json, but that's no longer there.

It seems like PuppetLabs has been changing the project_page to point to GitHub, so I've done that too, even though the change is arguable in my opinion ;-)

Changed in 3456192494936e2fefcdf5d190cad035248c9f4d, will be included in the next release.
