### ISSUE TITLE
FreeBSD Support

### ISSUE THREAD

**Issue by b4ldr** [thias/puppet-sysctl#27]
Hello,

This module says it supports freebsd on forge; however a quick looks suggests that it doesn't.  couple of examples
   * hard coded root group to 'root'.  FreeBSD uses 'wheel'
   * I don't think freebsd honors /etc/sysctl.d additions have to be added to the file /etc/sysctl.conf.local
Am i missing something?

**Comment by thias** [comment]
Most likely a copy/paste metadata.json leftover, sorry for that. I have removed it now. If you are interested in FreeBSD support, feel free to create a clean pull request for it. I personally only use Fedora and RHEL, but I'm always open to useful non-invasive changes.
