### ISSUE TITLE
${module_name} in sysctl/manifests/init.pp seems to be undefined in Puppet 4.2.0: "Failed to parse template /sysctl.d-file.erb"

### ISSUE THREAD

**Issue by synthead** [thias/puppet-sysctl#29]
Using sysctl in my own manifest results in this error:

    Error: Evaluation Error: Error while evaluating a Function Call, Failed to parse template /sysctl.d-file.erb:
      Filepath: /opt/puppetlabs/puppet/lib/ruby/vendor_ruby/puppet/file_system/file_impl.rb
      Line: 75
      Detail: No such file or directory @ rb_sysopen - /sysctl.d-file.erb
     at /root/puppet/modules/sysctl/manifests/init.pp:41:21 on node localhost.localdomain

Line 41 in `manifests/init.pp` contains:

        $file_content = template("${module_name}/sysctl.d-file.erb")

It appears as if ${module_name} is not being defined.  This occurs while running a masterless Puppet (my tree is in `/root/puppet` and I'm running `puppet apply --modulepath=/root/puppet/modules /root/puppet`).  A master/agent configuration has not been tested for this issue.

On RHEL 7.1 with Puppet Labs' puppet-agent-1.2.1-1.el7.x86_64 package.  `puppet help` reports `Puppet v4.2.0`.  thias-sysctl version 1.0.2 obtained via `puppet module install thias-sysctl`.

**Comment by thias** [comment]
I'm sorry, but after looking into this, you've most definitely hit a puppet bug. The `$module_name` variable is properly documented and should be available in your environment : 

https://docs.puppetlabs.com/puppet/latest/reference/lang_facts_and_builtin_vars.html#compiler-variables

```
$module_name — the name of the module that contains the current class or defined type.
```

If you are still experiencing the problem, I'd recommend reporting it upstream.
