### ISSUE TITLE
run sysctl on boot (ubuntu)

### ISSUE THREAD

**Issue by booo** [thias/puppet-sysctl#33]
On Ubuntu 14.04.3 LTS sysctl does not run on system boot as far as I can see. Can we add an option to enable a sysctl run when booting?

**Comment by thias** [comment]
I'm quite sure sysctl changes should be applied on boot. Maybe my module is changing things in the wrong places or something like that. I only use Fedora and RHEL so I wouldn't know, but feel free to investigate and create a pull request with details about what you've found and any relevant changes.
