### ISSUE TITLE
undefined method error in 1.0.3

### ISSUE THREAD

**Issue by dconry** [thias/puppet-sysctl#35]
Hi,

I am receiving an error when attempting to apply the latest version (1.0.3) of this module to a CentOS 6 host.  This error does not occur with the previous module version (1.0.2).  Detail:

_err: Could not retrieve catalog from remote server: Error 400 on SERVER: undefined method `length' for 0:Fixnum at /etc/puppet/environments/production/modules/sysctl/init.pp:87 at node ..._

The line in question in init.pp is a simple call to shellquote:

**$qvalue = shellquote($value)**

This function doesn't appear in the previous version, so I wonder if it's an issue with the type of $value being passed.  I don't have a lot of experience debugging such calls, but I'll try to investigate further as time allows.  For now I've rolled back to the previous release of thias-sysctl.

Thanks!

**Comment by thias** [comment]
Thanks for letting me know. I'm not seeing this error myself on hundreds of different RHEL 6 nodes (all 6.7 with puppet 3.7). If you're able to dig a bit more and at least identify the exact `$value` content causing this, it would be nice. I'm guessing you might have a numerical 0 where a string '0' would be expected...

**Comment by thias** [comment]
To know if my guess is correct, could you maybe try temporarily changing that line to this : 
```
$qvalue = shellquote("${value}")
```
This should force puppet to convert any numerical `$value` into a string.

**Comment by dconry** [comment]
That does indeed seem to be the case...  a $value of numerical 0 causes shellquote to choke due to lack of a .length method.

I could go through all of my YAML & change 0 to ! '0' or similar, but it seems the ${qvalue} is simply interpolated to a string directly below anyway.  I might use a wrapper module to translate any numerical input to a string, or modify the sysctl module code as you suggest for now.

Thanks for the analysis!

**Comment by dconry** [comment]
Modifying the code as you suggested does seem to resolve the issue with no bad effects.  For future sanity I've also quoted the $title param on previous line the same, but probably unnecessary.

Thanks again for the quick help.  Issue can be closed if desired, maybe the change could be considered for future releases...

**Comment by thias** [comment]
This should be fixed with 7b8bba2b7c99f137342e4565821b2f1e2bdc1afe and in 1.0.4 which I have just published to the Forge. Thanks again for your report!
