### ISSUE TITLE
Constant enforce related output.

### ISSUE THREAD

**Issue by mattpascoe** [thias/puppet-sysctl#37]
I've noticed I always get output for values with spaces in them. I believe the problem is that single values match fine but there needs to be escaped quotes around the qvalue on line 93 of init.pp

Something like:
`unless  => "/usr/bin/test \"$(/sbin/sysctl -n ${qtitle})\" = \"${qvalue}\"",`

**Comment by thias** [comment]
Thanks for the report! Fixed in 1.0.5.

**Comment by mattpascoe** [comment]
Ugg.. looks like I was not paying much attention.  You already did quote the thing using shellquote.  The problem actually seems to be that the res from sysctl -n contains tabs.. while the qvalue is just spaces.  I'll test an _actual_ fix here and give that to you.
